# Generated by Django 6.0.5 on 2026-05-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('computer_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('ALL_IN_ONE', 'All In One'), ('MINI_PC', 'Mini PC'), ('SERVER', 'Server')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ims_code', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(choices=[('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB')], max_length=10)),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=10)),
                ('storage_capacity', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('operating_system', models.CharField(choices=[('WINDOWS_10', 'Windows 10'), ('WINDOWS_11', 'Windows 11'), ('WINDOWS_7', 'Windows 7'), ('MACOS', 'macOS'), ('OTHER', 'Other')], max_length=30)),
                ('host_name', models.CharField(blank=True, max_length=150, null=True)),
                ('hotfix_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hotfix_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.computermodel')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('printer_type', models.CharField(choices=[('LASER', 'Laser'), ('INKJET', 'Inkjet'), ('DOT_MATRIX', 'Dot Matrix'), ('THERMAL', 'Thermal'), ('OTHER', 'Other')], max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ims_code', models.CharField(max_length=50, unique=True)),
                ('printer_name', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('printer_function', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.printermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
