# Generated by Django 6.0.5 on 2026-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='warranty_end_date',
            field=models.DateField(null=True),
        ),
    ]
