# Generated by Django 6.0.5 on 2026-05-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_printer_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ims_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
