# Generated by Django 6.0.5 on 2026-05-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_printer_ims_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='serial_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
