# Generated by Django 6.0.5 on 2026-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_computer_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ims_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
