# Generated by Django 6.0.5 on 2026-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_computer_ims_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='device_name',
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage_capacity',
            field=models.CharField(choices=[('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], max_length=10),
        ),
    ]
