# Generated by Django 6.0.5 on 2026-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_computer_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty_end_date',
            field=models.DateField(null=True),
        ),
    ]
