# Generated by Django 6.0.5 on 2026-08-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_computer_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='office_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
