# Generated by Django 6.0.5 on 2026-08-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_computer_contact_person_computer_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='office_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
