# Generated by Django 6.0.5 on 2026-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_printer_contact_person_printer_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='antivirus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='installed_applications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='security_hardening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='vendor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='antivirus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='installed_applications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='security_hardening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='vendor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
