# Generated by Django 6.0.5 on 2026-08-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_computer_antivirus_computer_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='host_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
