# Generated by Django 6.0.5 on 2026-08-16 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_brand_status_computermodel_status_department_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('computer_ims', models.CharField(blank=True, max_length=100, null=True)),
                ('log_type', models.CharField(choices=[('UPDATE', 'Update'), ('ERROR', 'Error'), ('MAINTENANCE', 'Maintenance'), ('ASSIGNMENT', 'Assignment'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='UPDATE', max_length=30)),
                ('description', models.TextField()),
                ('authorized_by', models.CharField(blank=True, max_length=150, null=True)),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolution_status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('IN_PROGRESS', 'In Progress')], default='RESOLVED', max_length=30)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.computer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
