# Generated by Django 6.0.5 on 2026-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_computerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlog',
            name='action_source',
            field=models.CharField(blank=True, default='Team Viewer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computerlog',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computerlog',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='computerlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerlog',
            name='log_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='computerlog',
            name='performer_role',
            field=models.CharField(blank=True, default='Senior Systems Administrator', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='computerlog',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
