# Generated by Django 6.0.5 on 2026-08-21 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_computerlog_action_source_computerlog_assigned_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('disposal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'Computer'), ('PRINTER', 'Printer')], default='COMPUTER', max_length=20)),
                ('asset_ims_code', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=200, null=True)),
                ('disposal_method', models.CharField(choices=[('AUCTION', 'Auction / Sale'), ('E_WASTE', 'E-Waste Recycling'), ('DONATION', 'Donation / Transfer'), ('SCRAP', 'Scrap / Cannibalize Parts'), ('DESTROYED', 'Physical Destruction'), ('WRITE_OFF', 'Write-Off / Loss'), ('RETURN_TO_VENDOR', 'Return to Vendor / Buyback')], default='E_WASTE', max_length=50)),
                ('disposal_reason', models.CharField(choices=[('OBSOLETE', 'End of Lifecycle / Obsolete'), ('BEYOND_ECONOMIC_REPAIR', 'Beyond Economic Repair'), ('PHYSICAL_DAMAGE', 'Irreparable Physical Damage'), ('UPGRADED', 'Replaced by New Hardware'), ('SECURITY_DECOMMISSION', 'Security Policy Decommission'), ('LOST_STOLEN', 'Lost or Stolen')], default='OBSOLETE', max_length=50)),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approval_reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('data_sanitized', models.BooleanField(default=True)),
                ('sanitization_method', models.CharField(choices=[('NIST_800_88', 'NIST SP 800-88 Purge/Clear'), ('DOD_5220_22_M', 'DoD 5220.22-M 3-Pass Wipe'), ('PHYSICAL_DESTRUCTION', 'Physical Degaussing / Shredding'), ('STORAGE_REMOVED', 'Storage Drive Physically Retained'), ('FACTORY_RESET', 'Factory Reset / Firmware Wipe'), ('NA', 'Not Applicable (Non-Storage Asset)')], default='NIST_800_88', max_length=50)),
                ('sanitized_by', models.CharField(blank=True, max_length=150, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_records', to='inventory.computer')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_records', to='inventory.printer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarrantyExtensionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('COMPUTER', 'Computer'), ('PRINTER', 'Printer')], default='COMPUTER', max_length=20)),
                ('contract_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer Standard Warranty'), ('EXTENDED', 'Extended Warranty'), ('AMC_COMPREHENSIVE', 'AMC - Comprehensive'), ('AMC_NON_COMPREHENSIVE', 'AMC - Non-Comprehensive'), ('ON_SITE_SLA', 'On-Site Priority Support SLA')], default='EXTENDED', max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('support_sla', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_extensions', to='inventory.computer')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_extensions', to='inventory.printer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
