# Generated by Django 6.0.5 on 2026-09-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_disposalrecord_warrantyextensionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyextensionrecord',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='warrantyextensionrecord',
            name='printer',
        ),
        migrations.AlterField(
            model_name='computer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ims_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.computermodel'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('WINDOWS_10', 'Windows 10'), ('WINDOWS_11', 'Windows 11'), ('WINDOWS_7', 'Windows 7'), ('MACOS', 'macOS'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(blank=True, choices=[('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage_capacity',
            field=models.CharField(blank=True, choices=[('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ims_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.printermodel'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_name',
            field=models.CharField(blank=True, default='Printer', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DisposalRecord',
        ),
        migrations.DeleteModel(
            name='WarrantyExtensionRecord',
        ),
    ]
