# Generated by Django 6.0.5 on 2026-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_warrantyextensionrecord_computer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20, null=True),
        ),
    ]
