# Generated by Django 6.0.5 on 2026-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_disposalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerlog',
            name='resolution_status',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('IN_PROGRESS', 'In Progress'), ('REFERRED_TO_DISPOSAL', 'Referred to Disposal')], default='RESOLVED', max_length=30),
        ),
    ]
